apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-mirror-test-aug27-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-mirror-test-aug27-gitops
    spec:  
      serviceAccountName: mirror-test-aug27-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=mirror-test-aug27-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/mirror-test-aug27-notebook -- git clone https://github.com/jdubrick-ai/mirror-test-aug27
      restartPolicy: Never