apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/instance: mirror-test-aug27-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  mirror-test-aug27-model-server
    app.kubernetes.io/part-of: mirror-test-aug27  
  name: mirror-test-aug27-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  mirror-test-aug27-model-server 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  mirror-test-aug27-model-server
    spec:
      containers:
      - image: quay.io/redhat-ai-dev/vllm-openai-ubi9:0.4.2
        args: [
            "--model",
            "Nondzu/Mistral-7B-code-16k-qlora",
            "--port",
            "8001",
            "--download-dir",
            "/models-cache",
            "--max-model-len",
            "6144"]
        resources:
          limits:
            nvidia.com/gpu: '1'
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models-cache
          mountPath: /models-cache
        name: app-model-service
        ports:
        - containerPort: 8001
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: models-cache
        persistentVolumeClaim:
          claimName: mirror-test-aug27

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
