apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mirror-test-aug27
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mirror-test-aug27 
  name: mirror-test-aug27
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mirror-test-aug27 
    weight: 100 
  wildcardPolicy: None
